name: ServerCore
version: 1.0
main: ServerCore
api-version: 1.20
commands:
  skyblockmenu:
    description: Opent het Skyblock eiland selectiemenu.
  shop:
    description: Opent de in-game server winkel.
  balance:
    description: Bekijk je huidige bankrekening.
  spawn:
    description: Teleporteer direct terug naar de spawn.
  claim:
    description: Informatie over het claimen van land.
