name: Minecraft Plugin Compiler

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Java 25 installeren
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: Plugin bouwen met Maven
        run: mvn -B clean package

      - name: Plugin JAR uploaden
        uses: actions/upload-artifact@v4
        with:
          name: TriCraftCore-Plugin
          path: target/TriCraftCore.jar
